Master depth calculation
sunflowerit/waftlib pull request #38
Opened 2023-09-08 15:34 UTC by gfcapalbo

Before building we run an update_depth script.

This is made to keep depths in waft updated.
If build is on it's first run the check will not happen. 

Deployed and testing on our internal nightly instance.

2023-09-13 09:28 UTC, gjotten requested changes

2023-09-13 09:28 UTC, gjotten commented on bin/update_depths.py
> +def main():
@gfcapalbo somewhere along the way the merge depth script seems to be deleting the empty lines in our repos.yaml file, messing with human readability:

![image](https://github.com/sunflowerit/waftlib/assets/19408699/b902eff1-428e-4986-9c92-81424a97a5cd)

2023-09-25 14:02 UTC, gfcapalbo commented on bin/update_depths.py
> +def main():
@gjotten Done. now all top level lines have a space before, with the happy side effect of removing duplicate lines . looks like this:

`odoo:
  defaults:
    depth: 108
  remotes:
    origin: https://github.com/OCA/OCB.git
    gfcapalbo: https://github.com/gfcapalbo/Odoo
  target: origin ${ODOO_VERSION}
  merges:
  - origin ${ODOO_VERSION}
  - gfcapalbo 14.0-backport-null-first-query-from-master
  - gfcapalbo 14.0-compute_notify_recipients-query-fix

therp/oe_bvtherp:
  defaults:
    depth: ${WAFT_DEPTH_MERGE}
  remotes:
    origin: git@gitlab.therp.nl:therp/oe_bvtherp.git
  merges:
  - origin ${ODOO_VERSION}
  - origin 14.0-#9929-portal_from_draft_to_discuss
  - origin 14.0-9964-use-web_widget_html_markdown

OCA/account-analytic:
  defaults:
    depth: ${WAFT_DEPTH_MERGE}
  remotes:
    origin: https://github.com/OCA/account-analytic
  merges:
  - origin ${ODOO_VERSION}

OCA/account-financial-reporting:
  defaults:
    depth: ${WAFT_DEPTH_MERGE}
  remotes:
    origin: https://github.com/OCA/account-financial-reporting
  merges:
  - origin ${ODOO_VERSION}

OCA/account-financial-tools:
  defaults:
    depth: 971
  remotes:
    origin: https://github.com/OCA/account-financial-tools
    ddejong: https://github.com/ddejong-therp/account-financial-tools
    gfcapalbo: https://github.com/gfcapalbo/account-financial-tools
  merges:
  - origin ${ODOO_VERSION}
  - ddejong ${ODOO_VERSION}-account_move_default_journal
  - gfcapalbo ${ODOO_VERSION}-error_management_chart_update

OCA/account-fiscal-rule:
  defaults:
    depth: ${WAFT_DEPTH_MERGE}
                                       `

2023-09-28 12:02 UTC, Hussam-Suleiman commented on build
> +pip install  --exists-action w -r "${ODOO_WORK_DIR}/requirements-default.txt" && \
@gfcapalbo why did you remove '--quiet'?

2023-09-28 15:40 UTC, gfcapalbo commented on build
> +pip install  --exists-action w -r "${ODOO_WORK_DIR}/requirements-default.txt" && \
restoring --quiet. i do not need that anymore.

2023-09-28 15:43 UTC, Hussam-Suleiman commented on build
> +pip install  --exists-action w -r "${ODOO_WORK_DIR}/requirements-default.txt" && \
I will merge this pull request for now, and in same time I am trying to upgrade it to the new version https://github.com/sunflowerit/waftlib/blob/v.23.08.03/.python-files/waft-update-depths .

2023-09-28 15:43 UTC, gfcapalbo commented
@gjotten  @Hussam-Suleiman requested changes  done

2023-09-28 15:48 UTC, Hussam-Suleiman commented
for now, I will merge the changes to master, and in same time I am working to upgrade it to the new version https://github.com/sunflowerit/waftlib/blob/v.23.08.03/.python-files/waft-update-depths .

2023-09-28 15:49 UTC, merged

2023-09-28 16:21 UTC, Hussam-Suleiman commented
@gfcapalbo it does not work for odoo 8 with python 2.7, did you test it with all odoo versions?
![image](https://github.com/sunflowerit/waftlib/assets/38970953/c49b2ec8-fcf4-4af5-88cf-621f3f266a8c)

2023-09-28 16:35 UTC, Hussam-Suleiman commented
after I merged this changes and then removed it from master again, I can't open this pull request again, @gfcapalbo do you have any idea?

2023-10-04 09:05 UTC, Hussam-Suleiman commented
@gfcapalbo @gjotten @NL66278 sorry for destroyed this pull request, we will continue on https://github.com/sunflowerit/waftlib/pull/40

2024-01-18 15:28 UTC, ddejong-therp commented on bin/update_depths.py
> +all_commits = {}
I see that this is never set?

2024-02-06 12:15 UTC, gfcapalbo commented
@Hussam-Suleiman replaced with MR:  https://github.com/sunflowerit/waftlib/pull/41

I have added an exit , if python version is not >= 3.5.
Script will just add a line "Depth update not supported for python < 3.5".

it was easier to manage it this way instead of writing a lot of different code to support python 2.7 wich is deprecated.

2024-02-06 13:49 UTC, gfcapalbo commented
@Hussam-Suleiman re-tested.  now script will exit when python is < 3.5 and the depth calculation will not be supported for older projects.... the error you had will not appear anymore.